# Generated by Django 2.1.7 on 2019-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190423_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='/default/default_avatar.png', null=True, upload_to='avatar/'),
        ),
    ]
