# Generated by Django 2.1.7 on 2019-04-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20190422_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='view_count'),
        ),
    ]
